kind: Deployment
apiVersion: apps/v1
metadata:
  name: multicluster-resiliency-addon-agent
  namespace: open-cluster-management-agent-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      addon: multicluster-resiliency-addon-agent
  template:
    metadata:
      labels:
        addon: multicluster-resiliency-addon-agent
    spec:
      containers:
        - name: multicluster-resiliency-addon-agent
          image: quay.io/ecosystem-appeng/multicluster-resiliency-addon:devel
          imagePullPolicy: Always
          args:
            - agent
