nameReference:
# reference service name to webhook configuration
- kind: Service
  fieldSpecs:
  - kind: ValidatingWebhookConfiguration
    path: webhooks/clientConfig/service/name

namePrefix:
  - kind: ValidatingWebhookConfiguration
    path: metadata/name
  - kind: Service
    path: metadata/name
  - kind: Service
    path: metadata/annotations/service.beta.openshift.io\/serving-cert-secret-name

namespace:
  # reference service namespace to webhook configuration
- kind: ValidatingWebhookConfiguration
  path: webhooks/clientConfig/service/namespace
