resources:
  - manifests.yaml
  - service.yaml

namePrefix: multicluster-resiliency-addon-

configurations:
  - kustomizeconfig.yaml

labels:
  - pairs:
      app.kubernetes.io/component: admission-webhook
