namespace: open-cluster-management

namePrefix: multicluster-resiliency-addon-

resources:
  - manifests.yaml
  - service.yaml

configurations:
  - kustomizeconfig.yaml

labels:
  - pairs:
      app.kubernetes.io/component: admission-webhook
