nameReference:
# reference service name to webhook configuration
- kind: Service
  fieldSpecs:
  - kind: ValidatingWebhookConfiguration
    path: webhooks/clientConfig/service/name

namespace:
  # reference service namespace to webhook configuration
- kind: ValidatingWebhookConfiguration
  path: webhooks/clientConfig/service/namespace
