---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-resilientcluster
  failurePolicy: Fail
  name: resilientcluster.appeng.ecosystem
  rules:
  - apiGroups:
    - appeng.ecosystem.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - resilientclusters
  sideEffects: None
