# selective injection of the name prefix
namePrefix:
  - kind: ServiceAccount
    path: metadata/name
  - kind: ClusterRole
    path: metadata/name
  - kind: ClusterRoleBinding
    path: metadata/name

nameReference:
  # copy service-account name to the appropriate label
  - kind: ServiceAccount
    fieldSpecs:
      - path: metadata/labels/app.kubernetes.io\/name
        kind: ServiceAccount
  # copy role name to the appropriate label
  - kind: ClusterRole
    fieldSpecs:
      - path: metadata/labels/app.kubernetes.io\/name
        kind: ClusterRole
  # copy role binding name to the appropriate label
  - kind: ClusterRoleBinding
    fieldSpecs:
      - path: metadata/labels/app.kubernetes.io\/name
        kind: ClusterRoleBinding
