apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .ResourceName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .ResourceName }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Group }}
