apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: multicluster-resiliency-addon
  namespace: replace-with-cluster-namespace
spec:
  installNamespace: open-cluster-management-agent-addon
  configs:
    - group: addon.open-cluster-management.io
      resource: addondeploymentconfigs
      name: deploy-config
      namespace: replace-with-cluster-namespace
