kind: Deployment
apiVersion: apps/v1
metadata:
  name: manager
  labels:
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      serviceAccountName: sa
      containers:
      - name: manager
        image: manager-image
        imagePullPolicy: IfNotPresent
        args:
          - manager
          - --agent-replicas=1
          - --controller-metric-address=:8080
          - --controller-probe-address=:8081
          - --controller-leader-election=false
