namespace: open-cluster-management
namePrefix: multicluster-resiliency-addon-
resources:
  - issuer.yaml
  - certificate.yaml
labels:
  - pairs:
      app.kubernetes.io/component: admission-webhook
configurations:
  - kustomizeconfig.yaml
