kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .ResourceName }}
rules:
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["managedclusteraddons"]
    verbs: ["get", "list", "watch"]
