# This kustomize file is used for kustomizing the Addon Manager deployment workload.
# Do not use directly, use as part of the overall Addon deployment (start at default).
resources:
- deployment.yaml
- clustermanagementaddon.yaml

namePrefix: multicluster-resiliency-addon-

configurations:
- kustomizeconfig.yaml

replacements:
- path: kustomizereplace.yaml

commonLabels:
  app.kubernetes.io/component: manager-workload

images:
- name: manager-image
  newName: quay.io/ecosystem-appeng/multicluster-resiliency-addon
  newTag: devel
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
