# Use the Addon Manager image as an argument to the manager so the same image will be used for the Addon Agent
# target text before replacement: '--agent-image=manager-image'
- source:
    fieldPath: spec.template.spec.containers.[name=manager].image
    kind: Deployment
  targets:
    - fieldPaths:
        - spec.template.spec.containers.[name=manager].args.1
      select:
        kind: Deployment
      options:
        delimiter: =
        index: 1
