apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

# note: namePrefix is enforced on selective resources, see kustomizeconfig
namePrefix: multicluster-resiliency-addon-

resources:
- ../rbac
- deployment.yaml
- clustermanagementaddon.yaml

images:
- name: manager-image
  newName: mcra-image
  newTag: replace-me
- name: mcra-image
  newName: quay.io/ecosystem-appeng/multicluster-resiliency-addon
  newTag: devel

configurations:
- kustomizeconfig.yaml

replacements:
- path: kustomizereplace.yaml
