# Use the Addon Manager image as an argument to the manager so the same image will be used for the Addon Agent
# target text before replacement: '--agent-image=manager-image'
- source:
    fieldPath: spec.template.spec.containers.[name=manager].image
    kind: Deployment
  targets:
    - fieldPaths:
        - spec.template.spec.containers.[name=manager].args.1
      select:
        kind: Deployment
      options:
        delimiter: =
        index: 1

# Create the appropriate name labels for the deployment
- source:
    fieldPath: metadata.name
    kind: Deployment
  targets:
    - fieldPaths:
        - metadata.labels.[app.kubernetes.io/name]
        - spec.selector.matchLabels.[app.kubernetes.io/name]
        - spec.template.metadata.labels.[app.kubernetes.io/name]
      select:
        kind: Deployment
      options:
        create: true

# Create the appropriate name label for teh cluster management addon
- source:
    fieldPath: metadata.name
    kind: ClusterManagementAddOn
  targets:
    - fieldPaths:
        - metadata.labels.[app.kubernetes.io/name]
      select:
        kind: ClusterManagementAddOn
      options:
        create: true
