apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

namePrefix: multicluster-resiliency-addon-

resources:
  - resources/clustermanagementaddon.yaml
  - resources/clusterrole.yaml
  - resources/serviceaccount.yaml
  - resources/clusterrolebinding.yaml
  - resources/deployment.yaml

images:
  - name: manager-image
    newName: quay.io/ecosystem-appeng/multicluster-resiliency-addon
    newTag: replace-me

configurations:
  - kustomizeconfig.yaml
