# This kustomize file is used for kustomizing the Addon Manager deployment workload.
# Do not use directly, use as part of the overall Addon deployment (start at default).
resources:
- deployment.yaml
- clustermanagementaddon.yaml

configurations:
- kustomizeconfig.yaml

replacements:
- path: kustomizereplace.yaml

commonLabels:
  app.kubernetes.io/component: manager-workload

images:
  - name: manager-image
    newName: manager-image
    newTag: replace-me
