apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

# note: namePrefix is enforced on selective resources, see kustomizeconfig
namePrefix: multicluster-resiliency-addon-

resources:
  - resources/clustermanagementaddon.yaml
  - resources/clusterrole.yaml
  - resources/serviceaccount.yaml
  - resources/clusterrolebinding.yaml
  - resources/deployment.yaml

images:
  - name: manager-image
    newName: mcra-image
    newTag: replace-me

configurations:
  - kustomizeconfig.yaml

replacements:
  - path: kustomizereplace.yaml
