# selective injection of the name prefix
namePrefix:
  - kind: Deployment
    path: metadata/name

nameReference:
   # copy deployment name to the appropriate labels and selectors
  - kind: Deployment
    fieldSpecs:
      - path: metadata/labels/app.kubernetes.io\/name
        kind: Deployment
      - path: spec/selector/matchLabels/app.kubernetes.io\/name
        kind: Deployment
      - path: spec/template/metadata/labels/app.kubernetes.io\/name
        kind: Deployment
