# selective injection of the name prefix
namePrefix:
  - kind: Deployment
    path: metadata/name

nameReference:
   # copy deployment name to the appropriate label
  - kind: Deployment
    fieldSpecs:
      - path: metadata/labels/app.kubernetes.io\/name
        kind: Deployment
